In [1]:
!pip install gdown

Defaulting to user installation because normal site-packages is not writeable
Collecting gdown
  Downloading gdown-3.12.2.tar.gz (8.2 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Requirement already satisfied: six in c:\program files\python38\lib\site-packages (from gdown) (1.15.0)
Collecting tqdm
  Downloading tqdm-4.50.2-py2.py3-none-any.whl (70 kB)
Requirement already satisfied: filelock in c:\program files\python38\lib\site-packages (from gdown) (3.0.12)
Requirement already satisfied: requests[socks] in c:\users\soumy\appdata\roaming\python\python38\site-packages (from gdown) (2.24.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\soumy\appdata\roaming\python\python38\site-packages (from requests[socks]->gdown) (1.25.10)
Requirement already satisfied: idna<3,>=2.5 in c:\users\soumy\appdata\roaming\python\python38\site-packages (from requests[socks]->gdown) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files\python38\lib\site-packages (from requests[socks]->gdown) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\soumy\appdata\roaming\python\python38\site-packages (from requests[socks]->gdown) (3.0.4)
Collecting PySocks!=1.5.7,>=1.5.6; extra == "socks"
  Downloading PySocks-1.7.1-py3-none-any.whl (16 kB)
Building wheels for collected packages: gdown
  Building wheel for gdown (PEP 517): started
  Building wheel for gdown (PEP 517): finished with status 'done'
  Created wheel for gdown: filename=gdown-3.12.2-py3-none-any.whl size=9684 sha256=2399ce2b3974509500b282c5f1df6d3caa1f68d81ad0bb28fbf780200851e2c9
  Stored in directory: c:\users\soumy\appdata\local\pip\cache\wheels\e2\62\1e\926d1ebe7b1e733c78d627fd288d01b83feaf67efc06e0e4c3
Successfully built gdown
Installing collected packages: tqdm, gdown, PySocks
Successfully installed PySocks-1.7.1 gdown-3.12.2 tqdm-4.50.2

In [2]:
# importing data
!gdown https://drive.google.com/uc?id=1ScF_1a-bkHi1qe8Rn78uxK6_5QwUD9Bu

Downloading...
From: https://drive.google.com/uc?id=1ScF_1a-bkHi1qe8Rn78uxK6_5QwUD9Bu
To: E:\Notebook\weatherHistory.csv

0.00B [00:00, ?B/s]
524kB [00:00, 3.46MB/s]
1.57MB [00:00, 3.72MB/s]
2.62MB [00:00, 4.62MB/s]
3.15MB [00:00, 4.70MB/s]
3.67MB [00:00, 4.75MB/s]
4.19MB [00:00, 4.81MB/s]
4.72MB [00:00, 4.82MB/s]
5.24MB [00:01, 4.86MB/s]
5.77MB [00:01, 4.86MB/s]
6.29MB [00:01, 4.88MB/s]
6.82MB [00:01, 4.88MB/s]
7.34MB [00:01, 4.89MB/s]
7.86MB [00:01, 4.90MB/s]
8.39MB [00:01, 4.90MB/s]
8.91MB [00:01, 4.91MB/s]
9.44MB [00:01, 4.90MB/s]
9.96MB [00:01, 4.91MB/s]
10.5MB [00:02, 4.92MB/s]
11.0MB [00:02, 4.93MB/s]
11.5MB [00:02, 4.88MB/s]
12.1MB [00:02, 4.90MB/s]
12.6MB [00:02, 4.90MB/s]
13.1MB [00:02, 4.91MB/s]
13.4MB [00:02, 5.00MB/s]

In [3]:
# Creating DataFrame object
import pandas as pd
df = pd.DataFrame(pd.read_csv('weatherHistory.csv'))

In [4]:
df.head(5)

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204,14.9569,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269,15.8263,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259,15.8263,1016.51,Partly cloudy throughout the day.

In [5]:
df.describe()

,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Pressure (millibars)
count,96453.000000,96453.000000,96453.000000,96453.000000,96453.000000,96453.000000,96453.000000
mean,11.932678,10.855029,0.734899,10.810640,187.509232,10.347325,1003.235956
std,9.551546,10.696847,0.195473,6.913571,107.383428,4.192123,116.969906
min,-21.822222,-27.716667,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.688889,2.311111,0.600000,5.828200,116.000000,8.339800,1011.900000
50%,12.000000,12.000000,0.780000,9.965900,180.000000,10.046400,1016.450000
75%,18.838889,18.838889,0.890000,14.135800,290.000000,14.812000,1021.090000
max,39.905556,39.344444,1.000000,63.852600,359.000000,16.100000,1046.380000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96453 entries, 0 to 96452
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Formatted Date            96453 non-null  object
 1   Summary                   96453 non-null  object
 2   Precip Type               95936 non-null  object
 3   Temperature (C)           96453 non-null  float64
 4   Apparent Temperature (C)  96453 non-null  float64
 5   Humidity                  96453 non-null  float64
 6   Wind Speed (km/h)         96453 non-null  float64
 7   Wind Bearing (degrees)    96453 non-null  int64
 8   Visibility (km)           96453 non-null  float64
 9   Pressure (millibars)      96453 non-null  float64
 10  Daily Summary             96453 non-null  object
dtypes: float64(6), int64(1), object(4)
memory usage: 8.1+ MB

In [9]:
df.columns

Index(['Formatted Date', 'Summary', 'Precip Type', 'Temperature (C)',
       'Apparent Temperature (C)', 'Humidity', 'Wind Speed (km/h)',
       'Wind Bearing (degrees)', 'Visibility (km)', 'Pressure (millibars)',
       'Daily Summary'],
      dtype='object')